### ISSUE TITLE
how to bundle/include all hi_score dependenices for an offline dev enivronment

### ISSUE THREAD

**Issue by jdmairs** [mmikowski/hi_score#10]
Back in 2014/16 we used node v4 and/or v6.  Based on the SPA book I was able to build my own web app.  Back then we used npmbox to essentially tar up all the node modules after they were completely resolved and installed on an internet connected dev machine and then sneaker net the "box" files over to the disconnected dev machine.  

In one fell swoop I would like todo the same thing for hi_score.  

I know npmbox is not supported since node v5.

Do you have any suggestions or experience with this?

Thanks!

John

**Comment by mmikowski** [comment]
I believe bin/xhi install will do everything you need there. It installs the npm files, places them in vendor directories, renames them per version, and patches them. Then one simple runs bin/xhi dev_start to access files your dev app page, e.g. app-tb02.html.  Please see bin/xhi help all or bin/xhi help all -v.

I will mark as closed but please reopen if I misunderstood. And again, thank you for your interest and support!
