### ISSUE TITLE
app-ex01 and 02 (non-build)creates blank pages due to missing libList entries

### ISSUE THREAD

**Issue by jdmairs** [mmikowski/hi_score#11]
xhi dev_start
firefox http://localhost:8080/app-ex01.html

fix: comment out 02_fake and add 02,03,04 extensions to 
'js/xhi/05_02_css_base.js',
'js/xhi/05_03_css_lb.js',
'js/xhi/05_04_css_shell.js',
'js/xhi/05_css.js',
 
ex01.08_app.js

**Comment by mmikowski** [comment]
This is fixed and tested in version 1.7.0, released last night.  Please reopen if you see issues. And thanks!
