### ISSUE TITLE
Failed test getTzCode

### ISSUE THREAD

**Issue by sbertault** [mmikowski/hi_score#16]
Just checked out hi_score / master, did
`$ bin/xhi build,dev_start`

I have a failed test in 00_xhi_libs.js 
```javascript
function getTzCode ( test_obj ) {
  var tz_code = utilObj._getTzCode_();
  test_obj.expect( __1 );

  // eslint-disable-next-line no-useless-escape
  test_obj.ok( tz_code.match( /^[A-Za-z0-9+\- ]+$/ ),
    'Code fails to match regex: ' + tz_code
  );
  test_obj.done();
}
```
`tz_code` is "GMT+01:00" and is no match for the regexp (due to the colon)

Environment :
Ubuntu 19.10
node v12.16.1
npm 6.13.4
Locale fr_FR.UTF-8

Thank you for the great work ; really looking forward to reading SPA 2nd ed.!

**Comment by mmikowski** [comment]
Thank you. We should add the colon. Sorry for the delayed response; been very busy with https://kfocus.org.

**Comment by mmikowski** [comment]
Colon added and tested.
