### ISSUE TITLE
Failed to build on MacOS Catalina

### ISSUE THREAD

**Issue by diachedelic** [mmikowski/hi_score#21]
Installing `pandoc` [was not enough](https://github.com/mmikowski/hi_score#macintosh-prerequisites), apparently I need to install some perl modules too. However, I do not know where to find them! I tried MacPorts but no dice:

```
$ sudo port install libgetopt-simple-perl libfile-slurp-perl
Error: Port libgetopt-simple-perl not found
$ sudo port install p5-libgetopt-simple p5-libfile-slurp
Error: Port p5-libgetopt-simple not found
```

# Log

```
$ bin/xhi build,dev_start
...
xhi> Distribtion directory exists. Wipe and recreate? (Y/n) Y
xhi>    02: Uglify JS and CSS...
xhi>    03: Save uglified JS and CSS...
xhi>    04: Superpack JS symbols...
xhi-error>  
*** PLEASE ADD PERL LIBRARIES ***
It appears the following perl libraries are not installed: 

sudo apt install libgetopt-simple-perl libfile-slurp-perl 

Please install and try again!


xhi-warn>  [Arguments] {}
xhi-abort>  Stage 11 build       : Fail
```

**Comment by mmikowski** [comment]
Sorry this didn't work for you. These are standard Perl libraries. But since I work on Linux only, I'm not sure what Brew uses for Perl installation. Let me know if you would like to reopen this.

**Comment by diachedelic** [comment]
Okay I will find out how to install standard Perl libraries on MacOS and try again. Thanks.

**Comment by diachedelic** [comment]
Running these commands were sufficient for `bin/xhi build,dev_start` to complete successfully.
```
# install cpanm
cpan App::cpanminus
# install missing modules
cpanm Getopt::Simple File::Slurp
```

**Comment by mmikowski** [comment]
Thank you.  I will add this to the README.md file.
