### ISSUE TITLE
Git clone command in README.md doesn't work

### ISSUE THREAD

**Issue by billzingler** [mmikowski/hi_score#3]
The command in the quick start yields this error: 
```
$ git clone git@github.com:mmikowski/hi_score.git
Cloning into 'hi_score'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

But I was able to clone with https:
```
$ git clone https://github.com/mmikowski/hi_score.git
Cloning into 'hi_score'...
remote: Counting objects: 1412, done.
remote: Total 1412 (delta 0), reused 0 (delta 0), pack-reused 1412
Receiving objects: 100% (1412/1412), 2.14 MiB | 795.00 KiB/s, done.
Resolving deltas: 100% (969/969), done.
Checking connectivity... done.
```
Thanks for your work on this!

Bill

**Comment by mmikowski** [comment]
I think all you need to do is add your SSH key to your Github.  [Here are the official instructions](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).  If you continue to see a problem you may check [this as well](https://help.github.com/articles/error-permission-denied-publickey/).

Please confirm whether or not this resolves this problem.

**Comment by mmikowski** [comment]
@billzingler I hope you are enjoying the project.  I am closing this with the assumption that everything is worked out.  Please re-open if you see an issue.  Cheers!
