### ISSUE TITLE
unable to run any bin/xhi commands

### ISSUE THREAD

**Issue by leokofi** [mmikowski/hi_score#6]
Hello

I am attempting to setup hi_score and I am getting the err below; am I missing something.
nodejs version v6.11.1; npm version: 3.10.10

command: bin/xhi install,setup

output:
/home/leo/test/heytest/bin/xhi:25
  makeReadPromFn = promisifyFn( fsObj.readFile ),
                   ^

TypeError: promisifyFn is not a function
    at Object.<anonymous> (/home/leo/test/heytest/bin/xhi:25:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

thanks

Leo

**Comment by mmikowski** [comment]
Hi Leokofi: I believe the error is due to the version of node. We are using version 8.x which includes the Promisify feature. Perhaps you might try the virtual appliance instead which has all the correct executables pre-installed?

**Comment by leokofi** [comment]
Hi.. i have tried it with node 8.x installed with NVM and I am getting the same error; also the link to the virtual application http://michaelmikowski.com/ova/kubuntu-17.04-hi_score-003-ova2.ova is giving me a 403 error forbidden.

I will try installing node straight without NVM and see how that goes.

thanks again... really looking forward to getting this to work.
Leo

**Comment by leokofi** [comment]
hi.. got it to start... now have to play with it..

thanks

Leo
