### ISSUE TITLE
example app-ex01 and app-ex02 build creates blank pages.

### ISSUE THREAD

**Issue by leokofi** [mmikowski/hi_score#7]
Hi Sir Michael

Just a quick note, for the app-ex01 and app-ex02 examples when you run bin/xhi build,dev_start you get an error in the terminal (everything works) and both app pages are blank, this is due to package.json line  682 app_table, looking for a file that is not in the js folder.

package.json -> line 695 "js/ex01-08_app-build.js" not in JS folder ; name in JS folder is ex01.08_app-build.js

package.json -> line 731 "js/ex02-08_app-build.js" not in JS folder ; name in JS folder is ex02.08_app-build.js

as result it generates an empty js/app-ex01-sp.js and js/app-ex02-sp.js once app is bulit.
Changing either the file name in package.json file or renaming the files in the JS folder fixes this.

thanks again.

Leo

**Comment by mmikowski** [comment]
Hi Leo:

Thanks for the help! This was indeed an issue and I have updated the package.json file to fix, NPM version 1.4.10, commit [master 05835f0]

Please review and close if you feel this looks good.

Cheers, Mike

**Comment by leokofi** [comment]
Hi Mike

I have checked package.json and it is still reflecting version 1.4.9; I haven't seen any push from your end go through, am I missing something.

Leo

**Comment by mmikowski** [comment]
Sorry, forgot to push. It's done now.  Please confirm.  Thanks Leo!

**Comment by leokofi** [comment]
Hey Mike... Thanks for the update... looks good to me..
